const { EMOJI } = require("./emojis");

// Catalogue unique des commandes du bot (préfixe "&"), partagé par &help ET
// &panel pour qu'ils ne puissent jamais se contredire (section 5/10/35 du
// cahier des charges : un seul système de permissions, pas une liste par
// endroit).
//
// 7 catégories thématiques (fusion de 12, demande explicite de refonte UX du
// &help : "maximum 6-7 catégories") — chacune porte un emoji et une
// description courte, affichés à l'accueil de &help SANS compteur de
// commandes (uniquement le nom + la description, plus lisible). Le filtrage
// par droit réel (utils/permissions/engine.js::can) reste appliqué à
// l'intérieur de chaque catégorie, inchangé.
//
// `permission` est une clé de utils/permissions/catalog.js, résolue via
// utils/permissions/engine.js::can(member, permission) — null = tout le
// monde. `prefix` vaut "main" (préfixe musique) ou "mod" (préfixe &).
// La musique est volontairement absente de ce catalogue : elle vit sur son
// propre préfixe, rappelé en pied de l'aide, et l'encombrait inutilement.
//
// IMPORTANT : ce catalogue contient DEUX types d'entrées, non distingués
// dans la forme (mêmes champs) mais différents dans le fond :
//   - des commandes RÉELLEMENT implémentées (voir utils/musicCommands.js
//     pour la table de dispatch) ;
//   - des commandes DOCUMENTÉES mais pas encore câblées à un handler —
//     demande explicite : le panel/l'aide doivent lister la référence
//     complète des commandes prévues, backend ou non ("intègre tout, même
//     sans backend, n'invente pas de permission juste pour l'affichage").
// Une commande sans handler dans modHandlers ne répond simplement rien si
// on la tape — comme n'importe quelle commande inconnue sur ce préfixe
// partagé avec le CrowBot. utils/helpPanel.js ne montre que les entrées
// RÉELLEMENT implémentées (voir utils/implementedCommands.js::isImplemented).
const CATEGORIES = [
  {
    key: "moderation",
    label: "Modération",
    emoji: EMOJI.BAN,
    description: "Sanctionner un membre",
    highlights: ["kick", "ban", "mute", "warn"],
    commands: [
      {
        name: "uo clear",
        prefix: null,
        permission: null,
        description: "Sans préfixe, efface tes propres messages du salon",
      },
      {
        name: "clear <@membre|id> [nombre]",
        prefix: "mod",
        permission: "moderation.clear",
        aliases: ["purge"],
        description: "Supprime les messages récents d'un membre précis dans le salon. La cible est obligatoire : sans elle, le bot laisse la main au CrowBot",
      },
      { name: "kick @membre [raison]", prefix: "mod", permission: "moderation.kick", description: "Expulse un membre" },
      {
        name: "ban <@membre|id> [raison]",
        prefix: "mod",
        permission: "moderation.ban",
        description: "Bannit un membre. La cible se donne par mention ou par identifiant",
      },
      {
        name: "unban [id]",
        prefix: "mod",
        permission: "moderation.unban",
        description: "Débannit un membre. Sans identifiant, propose la liste des bannis",
      },
      {
        name: "softban @membre [raison]",
        prefix: "mod",
        permission: "moderation.softban",
        description: "Bannit puis débannit aussitôt, purge les messages des dernières 24h",
      },
      {
        name: "timeout @membre <durée> [raison]",
        prefix: "mod",
        permission: "moderation.timeout",
        description: "Rend un membre muet (ex : `10m`, `1h`, `1d`)",
      },
      {
        name: "untimeout @membre",
        prefix: "mod",
        permission: "moderation.timeout",
        description: "Lève le timeout d'un membre",
      },
      {
        name: "banall [raison]",
        prefix: "mod",
        permission: "moderation.banall",
        description: "Bannit tout le serveur (confirmation obligatoire)",
      },
      {
        name: "banall message <texte>",
        prefix: "mod",
        permission: "moderation.banall",
        description: "Définit le message envoyé en DM à chacun avant d'être banni par &banall (aucun DM si rien n'est configuré)",
      },
      {
        name: "modlogs [@membre|id]",
        prefix: "mod",
        permission: "logs.view",
        description: "Consulte l'historique de modération",
      },
      {
        name: "lock [#salon]",
        prefix: "mod",
        permission: "channels.lock",
        description: "Empêche @everyone d'écrire dans le salon",
      },
      { name: "unlock [#salon]", prefix: "mod", permission: "channels.lock", description: "Rétablit l'écriture" },
      {
        name: "slowmode <durée|off> [#salon]",
        prefix: "mod",
        permission: "channels.slowmode",
        description: "Règle le mode lent (ex : `5s`, `1m`, `off`)",
      },
      { name: "hide", prefix: "mod", permission: "channels.manage", description: "Masque le salon à @everyone" },
      { name: "unhide", prefix: "mod", permission: "channels.manage", description: "Réaffiche le salon" },
      {
        name: "renew",
        prefix: "mod",
        permission: "channels.manage",
        description: "Recrée le salon à neuf (l'historique est perdu)",
      },
      {
        name: "lockdown",
        prefix: "mod",
        permission: "channels.lockdown",
        aliases: ["panic"],
        description: "Verrouille tous les salons gérables (urgence)",
      },
      { name: "unlockdown", prefix: "mod", permission: "channels.lockdown", description: "Lève un lockdown" },
      {
        name: "sanctions <membre>",
        prefix: "mod",
        permission: "logs.view",
        description: "Affiche les sanctions d'un membre",
      },
      {
        name: "del sanction <membre> <nombre>",
        prefix: "mod",
        permission: "logs.manage",
        description: "Supprime une sanction précise de l'historique d'un membre",
      },
      {
        name: "clear sanctions <membre>",
        prefix: "mod",
        permission: "logs.manage",
        description: "Supprime toutes les sanctions d'un membre",
      },
      {
        name: "clear all sanctions",
        prefix: "mod",
        permission: "logs.manage",
        description: "Supprime toutes les sanctions de tout le serveur",
      },
      {
        name: "warn <membre> [raison]",
        prefix: "mod",
        permission: "moderation.warn",
        description: "Avertit un membre (enregistré dans son historique, sans autre effet automatique)",
      },
      {
        name: "warnings <membre>",
        prefix: "mod",
        permission: "logs.view",
        description: "Affiche les avertissements d'un membre",
      },
      {
        name: "unwarn <membre> <numéro>",
        prefix: "mod",
        permission: "logs.manage",
        description: "Supprime un avertissement précis (voir `&warnings`)",
      },
      {
        name: "case <numéro>",
        prefix: "mod",
        permission: "logs.view",
        description: "Affiche le détail complet d'une sanction par son numéro de case",
      },
      {
        name: "mute <membre> [raison]",
        prefix: "mod",
        permission: "moderation.timeout",
        aliases: ["cmute"],
        description: "Rend un membre muet (rôle dédié à configurer via `set muterole`, distinct du timeout Discord)",
      },
      {
        name: "tempmute <membre> <durée> [raison]",
        prefix: "mod",
        permission: "moderation.timeout",
        aliases: ["tempcmute"],
        description: "Rend un membre muet temporairement",
      },
      {
        name: "unmute <membre>",
        prefix: "mod",
        permission: "moderation.timeout",
        aliases: ["uncmute"],
        description: "Lève le mute d'un membre",
      },
      {
        name: "mutelist",
        prefix: "mod",
        permission: "moderation.timeout",
        description: "Affiche la liste des membres actuellement mute",
      },
      {
        name: "unmuteall",
        prefix: "mod",
        permission: "moderation.unmuteall",
        description: "Lève le mute de tous les membres mute",
      },
      {
        name: "tempban <membre> <durée> [raison]",
        prefix: "mod",
        permission: "moderation.ban",
        description: "Bannit un membre temporairement, débanni automatiquement à l'échéance",
      },
      {
        name: "banlist",
        prefix: "mod",
        permission: "moderation.unban",
        description: "Affiche la liste des membres bannis",
      },
      {
        name: "hideall",
        prefix: "mod",
        permission: "channels.manageall",
        description: "Masque tous les salons gérables à @everyone",
      },
      {
        name: "unhideall",
        prefix: "mod",
        permission: "channels.manageall",
        description: "Réaffiche tous les salons masqués",
      },
      {
        name: "derank <membre>",
        prefix: "mod",
        permission: "members.role",
        description: "Retire tous les rôles d'un membre",
      },
      {
        name: "nick @membre <pseudo>",
        prefix: "mod",
        permission: "members.nick",
        description: "Change le pseudo d'un membre sur le serveur",
      },
      {
        name: "resetnick @membre",
        prefix: "mod",
        permission: "members.nick",
        description: "Rend à un membre son pseudo Discord d'origine",
      },
      {
        name: "unbanall",
        prefix: "mod",
        permission: "moderation.unbanall",
        description: "Débannit tout le monde (confirmation obligatoire)",
      },
      {
        name: "clear customs",
        prefix: "mod",
        permission: "server.channels.manage",
        description: "Supprime toutes les commandes personnalisées",
      },
      {
        name: "timeout <on/off>",
        prefix: "mod",
        permission: "protection.automod",
        description: "Active/désactive l'usage du timeout Discord comme sanction",
      },
      { name: "clear owners", prefix: "mod", permission: "sys", description: "Supprime tous les owners du bot" },
      {
        name: "clear bl",
        prefix: "mod",
        permission: "sys",
        description: "Supprime tous les membres de la blacklist du bot",
      },
    ],
  },
  {
    key: "securite",
    label: "Sécurité",
    emoji: EMOJI.LOCK,
    description: "Protection automatique et audit du serveur",
    highlights: ["antinuke", "antispam", "antilink", "badwords"],
    commands: [
      {
        name: "allbots",
        prefix: "mod",
        permission: "sys",
        description: "Liste paginée des comptes bot présents sur le serveur",
      },
      {
        name: "security scan",
        prefix: "mod",
        permission: "server.security.scan",
        description: "Audit de sécurité (permissions dangereuses, @everyone, bots admin, anti-nuke, AutoMod, logs, rôle de mute)",
      },
      {
        name: "alladmins",
        prefix: "mod",
        permission: "server.members.list",
        description: "Affiche la liste des membres (hors bots) ayant la permission administrateur",
      },
      {
        name: "botadmins",
        prefix: "mod",
        permission: "server.members.list",
        description: "Affiche la liste des bots ayant la permission administrateur",
      },
      {
        name: "antilink <on|off>",
        prefix: "mod",
        permission: "protection.automod",
        description: "Active/désactive la suppression automatique des liens",
      },
      {
        name: "antilink <invite|all>",
        prefix: "mod",
        permission: "protection.automod",
        description: "Règle le mode : invitations Discord seulement, ou tous les liens",
      },
      {
        name: "link <allow|deny|reset> [#salon]",
        prefix: "mod",
        permission: "protection.automod",
        description: "Exempte (ou non) un salon de l'anti-lien",
      },
      {
        name: "antimassmention <on|off>",
        prefix: "mod",
        permission: "protection.automod",
        description: "Active/désactive le timeout automatique en cas de mass-mention",
      },
      {
        name: "antimassmention <nombre>",
        prefix: "mod",
        permission: "protection.automod",
        description: "Règle le nombre de mentions maximum dans un message",
      },
      {
        name: "badwords <on|off>",
        prefix: "mod",
        permission: "protection.automod",
        description: "Active/désactive le filtre de mots interdits",
      },
      {
        name: "badwords add <mot>",
        prefix: "mod",
        permission: "protection.automod",
        description: "Ajoute un mot à la liste des mots interdits",
      },
      {
        name: "badwords del <mot>",
        prefix: "mod",
        permission: "protection.automod",
        description: "Retire un mot de la liste des mots interdits",
      },
      {
        name: "badwords list",
        prefix: "mod",
        permission: "protection.automod",
        description: "Affiche la liste des mots interdits",
      },
      {
        name: "badwords clear",
        prefix: "mod",
        permission: "protection.automod",
        description: "Vide la liste des mots interdits",
      },
      {
        name: "clear limit <nombre>",
        prefix: "mod",
        permission: "protection.automod",
        description: "Règle le nombre maximum de messages supprimables en une fois",
      },
      {
        name: "muterole",
        prefix: "mod",
        permission: "protection.automod",
        description: "Affiche le rôle de mute configuré",
      },
      {
        name: "set muterole <rôle>",
        prefix: "mod",
        permission: "protection.automod",
        description: "Configure le rôle utilisé par &mute/&tempmute",
      },
      {
        name: "antispam <on/off>",
        prefix: "mod",
        permission: "protection.automod",
        description: "Active/désactive l'anti-spam (voir aussi &panel > Protection)",
      },
      {
        name: "antispam <nombre>/<durée>",
        prefix: "mod",
        permission: "protection.automod",
        description: "Règle le seuil de déclenchement de l'anti-spam",
      },
      {
        name: "spam <allow/deny/reset> [salon]",
        prefix: "mod",
        permission: "protection.automod",
        description: "Exempte (ou non) un salon de l'anti-spam",
      },
      {
        name: "strikes",
        prefix: "mod",
        permission: "protection.automod",
        description: "Affiche le système de sanctions progressives (strikes)",
      },
      {
        name: "ancien <durée>",
        prefix: "mod",
        permission: "protection.automod",
        description: "Règle la durée avant qu'un strike soit considéré comme ancien",
      },
      {
        name: "strikes <déclencheur> <nombre> [ancien/nouveau]",
        prefix: "mod",
        permission: "protection.automod",
        description: "Configure le nombre de strikes déclenchant une sanction",
      },
      {
        name: "punish",
        prefix: "mod",
        permission: "protection.automod",
        description: "Affiche les paliers de sanction automatique configurés",
      },
      {
        name: "punish add <nombre> <durée> <sanction> [durée]",
        prefix: "mod",
        permission: "protection.automod",
        description: "Ajoute un palier de sanction automatique",
      },
      {
        name: "punish del <nombre>",
        prefix: "mod",
        permission: "protection.automod",
        description: "Retire un palier de sanction automatique",
      },
      {
        name: "punish setup",
        prefix: "mod",
        permission: "protection.automod",
        description: "Assistant de configuration des paliers de sanction",
      },
      {
        name: "noderank <add/del> <rôle>",
        prefix: "mod",
        permission: "protection.automod",
        description: "Exempte un rôle du &derank automatique",
      },
      {
        name: "piconly <add/del> [salon]",
        prefix: "mod",
        permission: "protection.automod",
        description: "Restreint un salon aux messages contenant une image",
      },
      {
        name: "public <on/off>",
        prefix: "mod",
        permission: "protection.automod",
        description: "Active/désactive le mode public d'un réglage",
      },
      {
        name: "public <allow/deny/reset> [salon]",
        prefix: "mod",
        permission: "protection.automod",
        description: "Exempte (ou non) un salon du mode public",
      },
      {
        name: "secur invite <on/off>",
        prefix: "mod",
        permission: "sys",
        description: "Le bot quitte automatiquement quand il rejoint un serveur sans le propriétaire",
      },
      {
        name: "antinuke [on|off|punishment|wlrole]",
        prefix: "mod",
        permission: "protection.guard.manage",
        description: "Anti-nuke : rafales de bans/kicks/salons/rôles/webhooks/bots détectées et sanctionnées automatiquement",
      },
      {
        name: "antinuke wluser <@membre/ID>",
        prefix: "mod",
        permission: "protection.guard.manage",
        description: "Exempte/retire un membre de l'anti-nuke (voir aussi &wl/&unwl)",
      },
      {
        name: "antinuke clearwl",
        prefix: "mod",
        permission: "protection.guard.manage",
        description: "Vide toute la whitelist anti-nuke (membres et rôles) d'un coup",
      },
      {
        name: "antinuke ping <rôle/off>",
        prefix: "mod",
        permission: "protection.guard.manage",
        description: "Ping un rôle en plus du log à chaque déclenchement d'un guard",
      },
      {
        name: "antinuke creationlimit <durée/off>",
        prefix: "mod",
        permission: "protection.guard.manage",
        description: "Sanctionne à l'arrivée les comptes créés il y a moins de cette durée",
      },
      {
        name: "antinuke autolockdown on|off",
        prefix: "mod",
        permission: "protection.guard.manage",
        description: "Verrouille tout le serveur (comme &lockdown) si l'anti-nuke atteint son plafond de sanctions par minute — désactivé par défaut",
      },
      {
        name: "whitelist",
        prefix: "mod",
        permission: "protection.whitelist",
        description: "Liste paginée des exemptés de l'anti-spam",
      },
      {
        name: "secur [off/on/max]",
        prefix: "mod",
        permission: "protection.guard.manage",
        description: "Affiche et/ou modifie tous les paramètres de l'antiraid sur le serveur",
      },
      {
        name: "antichannel <off/on/max>",
        prefix: "mod",
        permission: "protection.guard.manage",
        description: "Active/désactive l'antichannel",
      },
      {
        name: "antirole <off/on/max>",
        prefix: "mod",
        permission: "protection.guard.manage",
        description: "Active/désactive l'antirole",
      },
      {
        name: "antiwebhook <off/on/max>",
        prefix: "mod",
        permission: "protection.guard.manage",
        description: "Active/désactive l'antiwebhook",
      },
      {
        name: "antikick <off/on/max>",
        prefix: "mod",
        permission: "protection.guard.manage",
        description: "Rafale d'expulsions",
      },
      {
        name: "antichanneldelete <off/on/max>",
        prefix: "mod",
        permission: "protection.guard.manage",
        description: "Rafale de suppression de salons",
      },
      {
        name: "antiroledelete <off/on/max>",
        prefix: "mod",
        permission: "protection.guard.manage",
        description: "Rafale de suppression de rôles",
      },
      {
        name: "antiroleadmin <off/on/max>",
        prefix: "mod",
        permission: "protection.guard.manage",
        description: "Administrateur donné à un rôle",
      },
      {
        name: "antijoin <off/on/max>",
        prefix: "mod",
        permission: "protection.guard.manage",
        description: "Afflux de joins suspect",
      },
      {
        name: "antiunban <off/on/max>",
        prefix: "mod",
        permission: "protection.guard.manage",
        description: "Active/désactive l'antiunban",
      },
      {
        name: "antibot <off/on/max>",
        prefix: "mod",
        permission: "protection.guard.manage",
        description: "Active/désactive l'antibot",
      },
      {
        name: "antiban <off/on/max>",
        prefix: "mod",
        permission: "protection.guard.manage",
        description: "Active/désactive l'antiban",
      },
      {
        name: "antieveryone <off/on/max>",
        prefix: "mod",
        permission: "protection.guard.manage",
        description: "Active/désactive l'antieveryone",
      },
      {
        name: "creationlimit <off/on/max>",
        prefix: "mod",
        permission: "protection.guard.manage",
        description: "Active/désactive le guard \"compte trop récent\" (durée réglée séparément via &antinuke creationlimit)",
      },
      {
        name: "punition all <timeout/kick/ban>",
        prefix: "mod",
        permission: "protection.guard.manage",
        description: "Change la sanction appliquée par tous les guards",
      },
      {
        name: "wl <@membre/rôle/ID>",
        prefix: "mod",
        permission: "protection.guard.manage",
        description: "Ajoute quelqu'un (ou un rôle) à la whitelist anti-nuke",
      },
      {
        name: "unwl <@membre/rôle/ID>",
        prefix: "mod",
        permission: "protection.guard.manage",
        description: "Retire quelqu'un (ou un rôle) de la whitelist anti-nuke",
      },
    ],
  },
  {
    key: "serveurroles",
    label: "Serveur & Rôles",
    emoji: EMOJI.PENCIL,
    description: "Rôles, salons et vocaux",
    highlights: ["addrole", "role create", "channel create", "voc"],
    commands: [
      {
        name: "addrole @membre @rôle",
        prefix: "mod",
        permission: "members.role",
        description: "Ajoute un rôle à un membre",
      },
      {
        name: "delrole @membre @rôle",
        prefix: "mod",
        permission: "members.role",
        description: "Retire un rôle à un membre",
      },
      { name: "role create <nom>", prefix: "mod", permission: "server.roles.manage", description: "Crée un nouveau rôle" },
      {
        name: "role delete @rôle",
        prefix: "mod",
        permission: "server.roles.manage",
        description: "Supprime un rôle (confirmation obligatoire)",
      },
      { name: "role rename @rôle <nom>", prefix: "mod", permission: "server.roles.manage", description: "Renomme un rôle" },
      {
        name: "role color @rôle <hex>",
        prefix: "mod",
        permission: "server.roles.manage",
        description: "Change la couleur d'un rôle (ex : `#ff0000`)",
      },
      {
        name: "role admin @rôle",
        prefix: "mod",
        permission: "server.roles.admin_grant",
        description: "Donne/retire Administrateur à un rôle — jamais délégable par rôle, confirmation obligatoire",
      },
      {
        name: "massiverole [rôle] [rôle]",
        prefix: "mod",
        permission: "server.roles.manage",
        description: "Ajoute un ou plusieurs rôles à tous les membres",
      },
      {
        name: "unmassiverole [rôle] [rôle]",
        prefix: "mod",
        permission: "server.roles.manage",
        description: "Retire un ou plusieurs rôles à tous les membres",
      },
      {
        name: "temprole <membre> <rôle> <durée>",
        prefix: "mod",
        permission: "members.role",
        description: "Donne un rôle temporaire à un membre",
      },
      {
        name: "untemprole <membre> <rôle>",
        prefix: "mod",
        permission: "members.role",
        description: "Retire un rôle temporaire avant son échéance",
      },
      {
        name: "rolemenu [ID]",
        prefix: "mod",
        permission: "server.roles.manage",
        description: "Crée un menu de sélection de rôles",
      },
      {
        name: "autorole add @rôle",
        prefix: "mod",
        permission: "members.autorole.manage",
        description: "Ajoute un rôle donné automatiquement à chaque nouvel arrivant",
      },
      {
        name: "autorole del @rôle",
        prefix: "mod",
        permission: "members.autorole.manage",
        description: "Retire un rôle automatique",
      },
      {
        name: "autorole list",
        prefix: "mod",
        permission: "members.autorole.manage",
        description: "Liste les rôles automatiques configurés",
      },
      {
        name: "restrict <émoji> <rôle>",
        prefix: "mod",
        permission: "server.roles.manage",
        description: "Restreint l'usage d'un émoji à un rôle",
      },
      {
        name: "unrestrict <émoji>",
        prefix: "mod",
        permission: "server.roles.manage",
        description: "Retire la restriction d'un émoji",
      },
      {
        name: "channel create <nom> [vocal]",
        prefix: "mod",
        permission: "server.channels.manage",
        description: "Crée un nouveau salon",
      },
      {
        name: "channel delete [#salon]",
        prefix: "mod",
        permission: "server.channels.manage",
        description: "Supprime un salon (confirmation obligatoire)",
      },
      {
        name: "channel rename [#salon] <nom>",
        prefix: "mod",
        permission: "server.channels.manage",
        description: "Renomme un salon",
      },
      {
        name: "channel topic [#salon] <texte>",
        prefix: "mod",
        permission: "server.channels.manage",
        description: "Change le topic d'un salon",
      },
      {
        name: "dero [role @rôle|off]",
        prefix: "mod",
        permission: "server.dero.manage",
        description: "Applique automatiquement des permissions aux rôles configurés sur chaque nouveau salon",
      },
      {
        name: "create [émoji] [nom]",
        prefix: "mod",
        permission: "server.channels.manage",
        description: "Crée un émoji sur le serveur à partir d'un lien ou d'une pièce jointe",
      },
      {
        name: "newsticker [nom]",
        prefix: "mod",
        permission: "server.channels.manage",
        description: "Crée un sticker sur le serveur",
      },
      {
        name: "cleanup <salon>",
        prefix: "mod",
        permission: "server.channels.manage",
        description: "Nettoie les messages orphelins/indésirables d'un salon",
      },
      {
        name: "sync <salon/catégorie/all>",
        prefix: "mod",
        permission: "server.channels.manage",
        description: "Resynchronise les permissions d'un salon avec sa catégorie",
      },
      {
        name: "autoreact <add/del> <salon> <émoji>",
        prefix: "mod",
        permission: "server.channels.manage",
        description: "Ajoute/retire une réaction automatique sur les nouveaux messages d'un salon",
      },
      {
        name: "autoreact list",
        prefix: "mod",
        permission: "server.channels.manage",
        description: "Liste les réactions automatiques configurées",
      },
      {
        name: "autopublish <on/off>",
        prefix: "mod",
        permission: "server.channels.manage",
        description: "Publie automatiquement les messages dans les salons d'annonces",
      },
      {
        // Les actions vivent dans la description, plus dans le nom : la
        // syntaxe complète faisait 72 caractères et se retrouvait tronquée
        // à l'affichage, ce qui masquait justement la liste des actions.
        name: "voc <action> [valeur]",
        prefix: "mod",
        permission: null,
        // Formulée SANS " : " ni parenthèse : `resumer()` coupe la
        // description à la première des deux, ce qui escamoterait la liste
        // des actions — c'est-à-dire l'information utile de cette entrée.
        description: "lock, unlock, limit <n>, rename <nom>, kick, add, remove, transfer @membre — sur TON salon vocal temporaire",
      },
      {
        name: "voicehub #salon-vocal|off",
        prefix: "mod",
        permission: "server.voice.manage",
        description: "Rejoindre ce salon crée un salon vocal personnel temporaire",
      },
      {
        name: "voicemove [salon] [salon]",
        prefix: "mod",
        permission: "server.voice.moveall",
        description: "Déplace tous les membres d'un salon vocal vers un autre",
      },
      {
        name: "voicekick <membre>",
        prefix: "mod",
        permission: "server.voice.manage",
        description: "Expulse un membre du salon vocal",
      },
      {
        name: "bringall [salon]",
        prefix: "mod",
        permission: "server.voice.moveall",
        description: "Rassemble tous les membres connectés dans un même salon vocal",
      },
      {
        name: "tempvoc",
        prefix: "mod",
        permission: "server.voice.manage",
        description: "Affiche la configuration des salons vocaux temporaires (voir aussi &voicehub)",
      },
      {
        name: "tempvoc cmd",
        prefix: "mod",
        permission: "server.voice.manage",
        description: "Configure les commandes disponibles pour les salons vocaux temporaires",
      },
    ],
  },
  {
    key: "communaute",
    label: "Communauté",
    emoji: EMOJI.TICKET,
    description: "Tickets, annonces, sondages",
    highlights: ["ticket setup", "poll", "giveaway start", "embed"],
    commands: [
      {
        name: "ticket setup [@role-staff]",
        prefix: "mod",
        permission: "server.tickets.manage",
        description: "Poste le message \"Ouvrir un ticket\" dans le salon courant",
      },
      {
        name: "openmodmail <membre>",
        prefix: "mod",
        permission: "server.tickets.manage",
        description: "Ouvre un modmail avec un membre",
      },
      {
        name: "ticket settings",
        prefix: "mod",
        permission: "server.tickets.manage",
        description: "Affiche/configure les réglages des tickets",
      },
      {
        name: "claim",
        prefix: "mod",
        permission: "server.tickets.manage",
        description: "Prend en charge le ticket courant",
      },
      {
        name: "rename <nom>",
        prefix: "mod",
        permission: "server.tickets.manage",
        description: "Renomme le ticket courant",
      },
      {
        name: "add <membre>",
        prefix: "mod",
        permission: "server.tickets.manage",
        description: "Ajoute un membre au ticket courant",
      },
      {
        name: "del <membre>",
        prefix: "mod",
        permission: "server.tickets.manage",
        description: "Retire un membre du ticket courant",
      },
      {
        name: "close [raison]",
        prefix: "mod",
        permission: "server.tickets.manage",
        description: "Ferme le ticket courant",
      },
      {
        name: "modmail",
        prefix: "mod",
        permission: "server.tickets.manage",
        description: "Affiche/configure le système de modmail",
      },
      {
        name: "report settings",
        prefix: "mod",
        permission: "panel.permissions.manage",
        description: "Configure le système de signalement",
      },
      { name: "suggestion <message>", prefix: "mod", permission: null, description: "Poste une suggestion sur le serveur" },
      {
        name: "lb suggestions",
        prefix: "mod",
        permission: null,
        description: "Affiche les suggestions les mieux notées du serveur",
      },
      {
        name: "poll \"question\" \"option1\" \"option2\" [...]",
        prefix: "mod",
        permission: "server.polls.manage",
        description: "Sondage à boutons (2 à 5 options), un vote par personne",
      },
      {
        name: "giveaway start <durée> <lot>",
        prefix: "mod",
        permission: "server.giveaways.manage",
        description: "Lance un giveaway (ex : `giveaway start 1h Nitro`), tirage automatique au terme",
      },
      {
        name: "giveaway reroll [id]",
        prefix: "mod",
        permission: "server.giveaways.manage",
        description: "Retire un gagnant du dernier giveaway du salon",
      },
      {
        name: "end giveaway <id>",
        prefix: "mod",
        permission: "server.giveaways.manage",
        description: "Termine un giveaway avant son échéance",
      },
      {
        name: "choose <option1>,,<option2>,,...",
        prefix: "mod",
        permission: "server.tools.use",
        description: "Tire une option au hasard parmi celles données",
      },
      {
        name: "embed",
        prefix: "mod",
        permission: "server.channels.manage",
        description: "Ouvre un constructeur d'embed pour poster un message personnalisé",
      },
      {
        name: "button <add/del> <lien>",
        prefix: "mod",
        permission: null,
        description: "Ajoute/retire un bouton de lien sur le prochain message",
      },
      { name: "formulaire [ID]", prefix: "mod", permission: null, description: "Affiche ou crée un formulaire" },
      {
        name: "twitch",
        prefix: "mod",
        permission: "server.channels.manage",
        description: "Configure les annonces de live Twitch",
      },
      {
        name: "custom <mot-clé>",
        prefix: "mod",
        permission: "server.channels.manage",
        description: "Crée une commande personnalisée déclenchée par un mot-clé",
      },
      { name: "customlist", prefix: "mod", permission: null, description: "Liste les commandes personnalisées du serveur" },
      {
        name: "custom transfer <ID/nombre>",
        prefix: "mod",
        permission: "server.channels.manage",
        description: "Transfère une commande personnalisée",
      },
      {
        name: "suggestion settings",
        prefix: "mod",
        permission: "panel.permissions.manage",
        description: "Configure le système de suggestions",
      },
    ],
  },
  {
    key: "informations",
    label: "Informations",
    emoji: EMOJI.ONLINE,
    description: "Fiches, statistiques, journaux d'activité",
    highlights: ["userinfo", "server", "stats", "snipe"],
    commands: [
      {
        name: "settings",
        prefix: "mod",
        permission: "logs.manage",
        description: "Affiche un résumé des salons de logs configurés (voir aussi &panel > Logs) ; le résumé de l'anti-spam est dans &panel > Protection",
      },
      {
        name: "modlog on [salon]",
        prefix: "mod",
        permission: "logs.manage",
        description: "Active les logs de modération dans un salon",
      },
      { name: "modlog off", prefix: "mod", permission: "logs.manage", description: "Désactive les logs de modération" },
      {
        name: "messagelog on [salon]",
        prefix: "mod",
        permission: "logs.manage",
        description: "Active les logs de messages (édition/suppression) dans un salon",
      },
      { name: "messagelog off", prefix: "mod", permission: "logs.manage", description: "Désactive les logs de messages" },
      {
        name: "voicelog on [salon]",
        prefix: "mod",
        permission: "logs.manage",
        description: "Active les logs vocaux dans un salon",
      },
      { name: "voicelog off", prefix: "mod", permission: "logs.manage", description: "Désactive les logs vocaux" },
      {
        name: "boostlog on [salon]",
        prefix: "mod",
        permission: "logs.manage",
        description: "Active les logs de boost dans un salon",
      },
      { name: "boostlog off", prefix: "mod", permission: "logs.manage", description: "Désactive les logs de boost" },
      {
        name: "rolelog on [salon]",
        prefix: "mod",
        permission: "logs.manage",
        description: "Active les logs de rôles dans un salon",
      },
      { name: "rolelog off", prefix: "mod", permission: "logs.manage", description: "Désactive les logs de rôles" },
      {
        name: "memberlog on|off [salon]",
        prefix: "mod",
        permission: "logs.manage",
        description: "Logs des arrivées/départs et changements de membre",
      },
      {
        name: "channellog on|off [salon]",
        prefix: "mod",
        permission: "logs.manage",
        description: "Logs de création/suppression/édition de salons",
      },
      {
        name: "serverlog on|off [salon]",
        prefix: "mod",
        permission: "logs.manage",
        description: "Logs des réglages généraux du serveur",
      },
      {
        name: "botlog on|off [salon]",
        prefix: "mod",
        permission: "logs.manage",
        description: "Logs des bots ajoutés au serveur",
      },
      {
        name: "autoconfiglog",
        prefix: "mod",
        permission: "logs.manage",
        description: "Crée automatiquement les salons de logs manquants (voir aussi &panel > Logs)",
      },
      {
        name: "boostembed <on/off>",
        prefix: "mod",
        permission: "logs.manage",
        description: "Active/désactive l'embed d'annonce de boost",
      },
      {
        name: "boostembed test",
        prefix: "mod",
        permission: "logs.manage",
        description: "Envoie un aperçu de l'embed de boost",
      },
      {
        name: "nolog <add/del> [salon]",
        prefix: "mod",
        permission: "logs.manage",
        description: "Exempte (ou non) un salon des logs de messages",
      },
      {
        name: "pic [@membre]",
        prefix: "mod",
        permission: null,
        aliases: ["avatar"],
        description: "Affiche l'avatar d'un membre",
      },
      { name: "banner [@membre]", prefix: "mod", permission: null, description: "Affiche la bannière d'un membre" },
      {
        name: "server",
        prefix: "mod",
        permission: null,
        aliases: ["serverinfo"],
        description: "Affiche les informations du serveur (identifiant, propriétaire, membres, bots, salons, rôles, boosts)",
      },
      {
        name: "userinfo [@membre]",
        prefix: "mod",
        permission: null,
        aliases: ["member"],
        description: "Informations sur un membre (rôles, arrivée, timeout en cours)",
      },
      { name: "snipe", prefix: "mod", permission: null, description: "Affiche le dernier message supprimé du salon" },
      {
        name: "vc",
        prefix: "mod",
        permission: "server.stats.view",
        description: "Affiche le nombre de personnes actuellement en vocal",
      },
      {
        name: "stats",
        prefix: "mod",
        permission: "server.stats.view",
        description: "Affiche les statistiques du serveur (membres, en ligne, en vocal, en stream, actifs, mute)",
      },
      {
        name: "stats history [jours]",
        prefix: "mod",
        permission: "server.stats.view",
        description: "Évolution messages/arrivées/départs sur les N derniers jours (7 par défaut, 30 max)",
      },
      {
        name: "boosters",
        prefix: "mod",
        permission: "server.members.list",
        description: "Affiche la liste des membres boostant le serveur",
      },
      {
        name: "rolemembers <rôle>",
        prefix: "mod",
        permission: "server.members.list",
        description: "Affiche la liste des membres ayant un rôle précis (mention, ID ou nom)",
      },
      {
        name: "vocinfo",
        prefix: "mod",
        permission: "server.info.view",
        description: "Affiche les informations relatives à l'activité vocale du serveur",
      },
      {
        name: "role <rôle> (infos)",
        prefix: "mod",
        permission: "server.info.view",
        description: "Affiche les informations relatives à un rôle",
      },
      {
        name: "channel [salon] (infos)",
        prefix: "mod",
        permission: "server.info.view",
        description: "Affiche les informations relatives à un salon",
      },
      {
        name: "user [membre]",
        prefix: "mod",
        permission: "server.info.view",
        description: "Affiche les informations d'un compte Discord, même s'il n'est pas sur le serveur",
      },
      { name: "server pic", prefix: "mod", permission: null, description: "Permet de récupérer l'icône du serveur" },
      { name: "server banner", prefix: "mod", permission: null, description: "Permet de récupérer la bannière du serveur" },
      {
        name: "emoji <émoji>",
        prefix: "mod",
        permission: "server.info.view",
        description: "Récupère l'image d'un émoji personnalisé (émoji, nom ou ID), y compris venu d'un autre serveur",
      },
      {
        name: "server list",
        prefix: "mod",
        permission: "sys",
        description: "Affiche la liste des serveurs où se trouve le bot",
      },
    ],
  },
  {
    key: "outils",
    label: "Outils",
    emoji: EMOJI.ARROW,
    description: "Calcul, wiki, sauvegardes du serveur",
    highlights: ["calc", "wiki", "backup", "backup list"],
    commands: [
      {
        name: "image <mot-clé>",
        prefix: "mod",
        permission: null,
        description: "Fait une recherche google image avec le bot",
      },
      {
        name: "wiki <mot-clé>",
        prefix: "mod",
        permission: "server.tools.use",
        description: "Affiche le résumé de l'article Wikipédia (fr) correspondant",
      },
      {
        name: "search wiki <mot-clé>",
        prefix: "mod",
        permission: "server.tools.use",
        description: "Permet de voir tous les articles wikipedia relatifs au mot-clé donné",
      },
      {
        name: "calc <calcul>",
        prefix: "mod",
        permission: null,
        description: "Résout un calcul (parenthèses, puissances, sqrt/abs/ln/sin...) ou une équation du premier degré en `x`",
      },
      {
        name: "loading <durée> <message>",
        prefix: "mod",
        permission: null,
        description: "Affiche une barre de chargement animée",
      },
      { name: "reminder [nombre]", prefix: "mod", permission: null, description: "Programme un rappel" },
      { name: "reminder list", prefix: "mod", permission: null, description: "Liste tes rappels programmés" },
      {
        name: "show pics",
        prefix: "mod",
        permission: null,
        description: "Affiche/masque les photos de profil dans certains affichages",
      },
      {
        name: "backup <nom>",
        prefix: "mod",
        permission: "sys",
        description: "Sauvegarde la structure du serveur (catégories, salons, ordre, limites de places vocales — pas les permissions ni les messages)",
      },
      { name: "backup list", prefix: "mod", permission: "sys", description: "Liste les sauvegardes disponibles" },
      { name: "backup delete <nom>", prefix: "mod", permission: "sys", description: "Supprime une sauvegarde" },
      {
        name: "backup load <nom>",
        prefix: "mod",
        permission: "sys",
        description: "Restaure une sauvegarde dans ce serveur (confirmation obligatoire)",
      },
      {
        name: "autobackup <serveur/emoji> <jours>",
        prefix: "mod",
        permission: "sys",
        description: "Programme une sauvegarde automatique périodique",
      },
    ],
  },
  {
    key: "bot",
    label: "Bot & Accès",
    emoji: EMOJI.DISCORD,
    description: "Réglages du bot, accès, rang sys",
    highlights: ["panel", "prefix", "status", "perms"],
    commands: [
      {
        name: "status",
        prefix: "mod",
        permission: "sys",
        description: "Diagnostics techniques du bot (uptime, latence, mémoire, versions, état des nœuds Lavalink)",
      },
      { name: "help", prefix: "mod", permission: null, description: "Ouvre le centre de commandes : tout ce que tu peux taper, classé par palier" },
      { name: "changelogs", prefix: "mod", permission: null, description: "Affiche les dernières notes de mise à jour" },
      {
        name: "support",
        prefix: "mod",
        permission: null,
        description: "Donne un lien d'invitation vers le serveur de support du bot",
      },
      {
        name: "perms",
        prefix: "mod",
        permission: "panel.permissions.manage",
        description: "Affiche les paliers de permissions accordés (rôles ayant les mêmes droits) et les commandes qu'ils débloquent",
      },
      {
        name: "helpall",
        prefix: "mod",
        permission: "panel.permissions.manage",
        description: "Affiche les paliers de permissions accordés et les rôles associés à chacun",
      },
      {
        name: "autodelete <moderation/snipe> <commande/reply> <on/off/durée>",
        prefix: "mod",
        permission: "panel.permissions.manage",
        description: "Règle la suppression automatique des réponses du bot",
      },
      {
        name: "join settings",
        prefix: "mod",
        permission: "server.welcome.manage",
        description: "Affiche/configure les réglages d'arrivée (voir aussi la rubrique Bienvenue)",
      },
      {
        name: "leave settings",
        prefix: "mod",
        permission: "server.welcome.manage",
        description: "Affiche/configure les réglages de départ",
      },
      {
        name: "verify setup [@rôle]",
        prefix: "mod",
        permission: "members.verification.manage",
        description: "Règle (si donné) le rôle de vérification et poste le bouton \"Se vérifier\" dans le salon courant",
      },
      { name: "soutien", prefix: "mod", permission: null, description: "Affiche les informations de soutien du bot" },
      {
        name: "set perm <permission/commande> <rôle/membre>",
        prefix: "mod",
        permission: "panel.permissions.manage",
        description: "Accorde une permission à un rôle ou un membre (voir aussi la rubrique Permissions)",
      },
      {
        name: "del perm <rôle>",
        prefix: "mod",
        permission: "panel.permissions.manage",
        description: "Retire les permissions accordées à un rôle",
      },
      {
        name: "clear perms",
        prefix: "mod",
        permission: "panel.permissions.manage",
        description: "Réinitialise toutes les permissions accordées",
      },
      {
        name: "prefix <préfixe>",
        prefix: "mod",
        permission: "sys",
        description: "Change le préfixe des commandes (voir aussi la rubrique Préfixes)",
      },
      {
        name: "set modlogs",
        prefix: "mod",
        permission: "logs.manage",
        description: "Règle le salon de logs de modération (voir aussi &panel > Logs)",
      },
      {
        name: "set boostembed",
        prefix: "mod",
        permission: "logs.manage",
        description: "Personnalise l'embed d'annonce de boost",
      },
      {
        name: "panel",
        prefix: "mod",
        permission: null,
        description: "Panneau de configuration (rubriques visibles selon tes droits)",
      },
      {
        name: "sources [titre ou lien]",
        prefix: "mod",
        permission: "sys",
        description: "Dit d'où le son peut encore venir quand un morceau refuse de se lire",
      },
      {
        name: "owners",
        prefix: "mod",
        permission: "sys",
        description: "Liste paginée du rang sys ; ajout/retrait réservés au propriétaire du bot",
      },
      { name: "set name <nom>", prefix: "mod", permission: "sys", description: "Change le nom du bot" },
      {
        name: "set pic <lien>",
        prefix: "mod",
        permission: "sys",
        description: "Change la photo de profil du bot (lien ou pièce jointe)",
      },
      {
        name: "set banner <lien>",
        prefix: "mod",
        permission: "sys",
        description: "Change la bannière du bot (lien ou pièce jointe)",
      },
      {
        name: "set profil",
        prefix: "mod",
        permission: "sys",
        description: "Permet de modifier d'un coup le profil du bot",
      },
      {
        name: "playto|listen|watch|compet|stream <message>",
        prefix: "mod",
        permission: "sys",
        description: "Change l'activité du bot ; plusieurs phrases séparées par `,,` alternent",
      },
      { name: "remove activity", prefix: "mod", permission: "sys", description: "Supprime l'activité du bot" },
      { name: "online|idle|dnd|invisible", prefix: "mod", permission: "sys", description: "Change le statut du bot" },
      {
        name: "mp settings",
        prefix: "mod",
        permission: "sys",
        description: "Permet de gérer les messages privés envoyés par le bot",
      },
      {
        name: "invite <ID/nombre>",
        prefix: "mod",
        permission: "sys",
        description: "Envoie une invitation pour un serveur où se trouve le bot",
      },
      { name: "leave [ID/nombre]", prefix: "mod", permission: "sys", description: "Fait quitter un serveur au bot" },
      {
        name: "discussion <ID/nombre>",
        prefix: "mod",
        permission: "sys",
        description: "Permet de discuter à travers le bot sur un serveur où il se trouve",
      },
      { name: "mp <membre> <message>", prefix: "mod", permission: "sys", description: "Envoie un mp à un membre" },
      { name: "fivem", prefix: "mod", permission: "sys", description: "Permet de connecter le bot à ton serveur FiveM" },
      {
        name: "owner <@membre/ID>",
        prefix: "mod",
        permission: "sys",
        description: "Donne le grade Owner à quelqu'un sur le bot, il aura toutes les permissions dessus",
      },
      { name: "unowner <@membre/ID>", prefix: "mod", permission: "sys", description: "Retire le grade Owner à quelqu'un" },
      {
        name: "bl <@membre/ID> [raison]",
        prefix: "mod",
        permission: "sys",
        description: "Ajoute quelqu'un à la blacklist, il sera banni de tous les serveurs où le bot se trouve",
      },
      { name: "bl (liste)", prefix: "mod", permission: "sys", description: "Affiche la blacklist du bot" },
      {
        name: "unbl <@membre/ID>",
        prefix: "mod",
        permission: "sys",
        description: "Retire quelqu'un de la blacklist du bot",
      },
      {
        name: "blinfo <@membre/ID>",
        prefix: "mod",
        permission: "sys",
        description: "Affiche toutes les informations concernant la blacklist d'un membre",
      },
      { name: "say <message>", prefix: "mod", permission: "sys", description: "Fait dire au bot le message voulu" },
      {
        name: "change <commande> <permission>",
        prefix: "mod",
        permission: "sys",
        description: "Change la permission nécessaire pour utiliser une commande",
      },
      {
        name: "changeall <permission> <permission>",
        prefix: "mod",
        permission: "sys",
        description: "Transfère toutes les commandes d'une permission vers une autre",
      },
      {
        name: "change reset",
        prefix: "mod",
        permission: "sys",
        description: "Réinitialise les permissions pour toutes les commandes",
      },
      {
        name: "mainprefix <préfixe>",
        prefix: "mod",
        permission: "sys",
        description: "Change le préfixe par défaut du bot",
      },
      {
        name: "helptype <button/select/hybrid>",
        prefix: "mod",
        permission: "sys",
        description: "Change le mode de navigation du menu help entre boutons, sélecteur ou les deux",
      },
      {
        name: "alias <commande>",
        prefix: "mod",
        permission: "sys",
        description: "Permet de créer des alias pour les commandes",
      },
      {
        name: "helpalias <on/off>",
        prefix: "mod",
        permission: "sys",
        description: "Active/désactive l'utilisation des alias dans les messages de help",
      },
      { name: "set lang <langue>", prefix: "mod", permission: "sys", description: "Change la langue du bot" },
      {
        name: "lang custom [on/off/fichier]",
        prefix: "mod",
        permission: "sys",
        description: "Permet de modifier le fichier de langue du bot",
      },
      {
        name: "get lang",
        prefix: "mod",
        permission: "sys",
        description: "Affiche les fichiers de configuration de langue actuels",
      },
      {
        name: "updatebot",
        prefix: "mod",
        permission: "sys",
        description: "Installe les dernières mises à jour disponibles sur le bot",
      },
      { name: "autoupdate <on/off>", prefix: "mod", permission: "sys", description: "Active/désactive l'autoupdate" },
      {
        name: "reset server",
        prefix: "mod",
        permission: "sys",
        description: "Réinitialise tous les paramètres du bot sur un serveur",
      },
      { name: "resetall", prefix: "mod", permission: "sys", description: "Réinitialise l'ensemble des paramètres du bot" },
    ],
  },
];

/**
 * Catégories réellement utilisables par quelqu'un, commandes filtrées selon
 * ses droits ET réellement implémentées. Une catégorie dont rien n'est
 * accessible n'apparaît pas.
 * @param {(permission: string|null) => boolean} canUse
 */
function categoriesFor(canUse) {
  const { isImplemented } = require("./implementedCommands");
  return CATEGORIES.map((category) => ({
    ...category,
    commands: category.commands.filter((cmd) => isImplemented(cmd) && canUse(cmd.permission)),
  })).filter((category) => category.commands.length > 0);
}

module.exports = { CATEGORIES, categoriesFor };
