// Catalogue du système "Tools" (préfixe ";", voir utils/prefixStore.js) —
// volontairement séparé de utils/commandCatalog.js (préfixe "&") : deux
// systèmes de commandes distincts, jamais mélangés (demande explicite).
//
// Comme utils/commandCatalog.js : `permission` est une clé de
// utils/permissions/catalog.js ou null (tout le monde). La plupart des
// entrées ici sont de la DOCUMENTATION (pas encore de handler câblé) — voir
// la note en tête de utils/commandCatalog.js, même principe. Le texte
// original ne fournissait pas de description pour ces commandes (juste la
// syntaxe) : les descriptions ci-dessous sont donc rédigées à partir du nom
// de la commande, pas recopiées d'une source.
const CATEGORIES = [
  {
    key: "stats",
    label: "Statistiques",
    commands: [
      { name: "compteur", prefix: "tools", permission: null, description: "Configure des salons vocaux affichant des statistiques en temps réel (membres, boosts...)" },
      { name: "graph [arguments]", prefix: "tools", permission: null, description: "Affiche un graphique d'évolution des statistiques du serveur" },
      { name: "inactif <temps>", prefix: "tools", permission: null, description: "Liste les membres inactifs depuis une durée donnée" },
      { name: "list bday", prefix: "tools", permission: null, description: "Liste les anniversaires enregistrés sur le serveur" },
      { name: "poll [id]", prefix: "tools", permission: null, description: "Affiche les résultats d'un sondage de statistiques" },
      { name: "reset all stats", prefix: "tools", permission: null, description: "Réinitialise toutes les statistiques du serveur" },
      { name: "role ancient add <role> <temps>", prefix: "tools", permission: null, description: "Attribue un rôle aux membres présents depuis une ancienneté donnée" },
      { name: "role ancient cumul <on/off>", prefix: "tools", permission: null, description: "Active/désactive le cumul des rôles d'ancienneté" },
      { name: "role ancient del <role>", prefix: "tools", permission: null, description: "Retire un rôle d'ancienneté configuré" },
      { name: "role ancient list", prefix: "tools", permission: null, description: "Liste les rôles d'ancienneté configurés" },
      { name: "role badge add <badge> <role>", prefix: "tools", permission: null, description: "Associe un rôle à un badge de profil" },
      { name: "role badge del <badge>", prefix: "tools", permission: null, description: "Retire l'association d'un badge" },
      { name: "role badge list", prefix: "tools", permission: null, description: "Liste les associations badge/rôle configurées" },
      { name: "role bday [role]", prefix: "tools", permission: null, description: "Configure le rôle attribué le jour de l'anniversaire d'un membre" },
      { name: "role boost add <role> <temps>", prefix: "tools", permission: null, description: "Attribue un rôle aux boosters selon leur ancienneté de boost" },
      { name: "role boost cumul <on/off>", prefix: "tools", permission: null, description: "Active/désactive le cumul des rôles de boost" },
      { name: "role boost del <role>", prefix: "tools", permission: null, description: "Retire un rôle de boost configuré" },
      { name: "role boost list", prefix: "tools", permission: null, description: "Liste les rôles de boost configurés" },
      { name: "role voc", prefix: "tools", permission: null, description: "Configure un rôle attribué pendant la présence en vocal" },
      { name: "settings global", prefix: "tools", permission: null, description: "Affiche l'ensemble des réglages du module Statistiques" },
      { name: "star allow <role>", prefix: "tools", permission: null, description: "Autorise un rôle à faire briller un message (starboard)" },
      { name: "star deny <role>", prefix: "tools", permission: null, description: "Retire l'autorisation d'un rôle pour le starboard" },
      { name: "star off <voc/msg> <jour/semaine>", prefix: "tools", permission: null, description: "Désactive un classement star (vocal ou messages) sur une période" },
      { name: "star on <voc/msg> <jour/semaine> <role>", prefix: "tools", permission: null, description: "Active un classement star (vocal ou messages) sur une période, avec un rôle de récompense" },
      { name: "star roles", prefix: "tools", permission: null, description: "Liste les rôles de récompense star configurés" },
      { name: "starboard", prefix: "tools", permission: null, description: "Configure le salon et le seuil de réactions du starboard" },
      { name: "statembed", prefix: "tools", permission: null, description: "Configure l'apparence des embeds de statistiques" },
      { name: "stats best [temps]", prefix: "tools", permission: null, description: "Affiche le classement des membres les plus actifs" },
      { name: "stats channel [salon]", prefix: "tools", permission: null, description: "Affiche les statistiques d'un salon" },
      { name: "stats server", prefix: "tools", permission: null, description: "Affiche les statistiques du serveur" },
      { name: "stats user [membre]", prefix: "tools", permission: null, description: "Affiche les statistiques d'un membre" },
    ],
  },
  {
    key: "levels",
    label: "Levels",
    commands: [
      { name: "cooldown <temps>", prefix: "tools", permission: "server.levels.manage", description: "Règle le délai minimum entre deux gains d'XP par message" },
      { name: "leaderboard level", prefix: "tools", permission: null, description: "Affiche le classement des niveaux du serveur" },
      { name: "level [membre]", prefix: "tools", permission: null, description: "Affiche le niveau et l'XP d'un membre" },
      { name: "levelcard", prefix: "tools", permission: null, description: "Alias de `level` (pas de rendu image dédié)" },
      { name: "lvlmessage off", prefix: "tools", permission: "server.levels.manage", description: "Désactive l'annonce de passage de niveau" },
      { name: "lvlmessage on [salon]", prefix: "tools", permission: "server.levels.manage", description: "Active l'annonce de passage de niveau dans un salon" },
      { name: "lvlmessage set <message>", prefix: "tools", permission: "server.levels.manage", description: "Personnalise le message de passage de niveau" },
      { name: "rate level <niveau>", prefix: "tools", permission: "server.levels.manage", description: "Affiche le niveau requis pour un total d'XP donné" },
      { name: "rate list", prefix: "tools", permission: "server.levels.manage", description: "Liste les multiplicateurs d'XP configurés par salon" },
      { name: "rate message <rate> [salon]", prefix: "tools", permission: "server.levels.manage", description: "Règle le multiplicateur d'XP des messages pour un salon" },
      { name: "rate mute <pourcentage> [salon]", prefix: "tools", permission: "server.levels.manage", description: "Réduit le gain d'XP d'un pourcentage pour un salon" },
      { name: "rate voc <rate> [salon]", prefix: "tools", permission: "server.levels.manage", description: "Règle le multiplicateur d'XP vocal pour un salon" },
      { name: "role level add <role> <niveau>", prefix: "tools", permission: "server.levels.manage", description: "Attribue un rôle à partir d'un niveau donné" },
      { name: "role level cumul <on/off>", prefix: "tools", permission: "server.levels.manage", description: "Active/désactive le cumul des rôles de niveau" },
      { name: "role level del <role>", prefix: "tools", permission: "server.levels.manage", description: "Retire un rôle de niveau configuré" },
      { name: "role level list", prefix: "tools", permission: "server.levels.manage", description: "Liste les rôles de niveau configurés" },
      { name: "settings level", prefix: "tools", permission: "server.levels.manage", description: "Affiche l'ensemble des réglages du module Levels" },
      { name: "xp add <nombre> [membre]", prefix: "tools", permission: "server.levels.manage", description: "Ajoute de l'XP à un membre" },
      { name: "xp remove <nombre> [membre]", prefix: "tools", permission: "server.levels.manage", description: "Retire de l'XP à un membre" },
      { name: "xp reset <membre>", prefix: "tools", permission: "server.levels.manage", description: "Réinitialise l'XP d'un membre" },
      { name: "xp resetall", prefix: "tools", permission: "server.levels.manage", description: "Réinitialise l'XP de tout le serveur" },
    ],
  },
  {
    key: "invites",
    label: "Invitations",
    commands: [
      { name: "event [membre]", prefix: "tools", permission: null, description: "Affiche le compteur d'événements d'un membre" },
      { name: "fakelimit <limite>", prefix: "tools", permission: "server.levels.manage", description: "Règle le seuil à partir duquel une invitation est considérée comme fausse" },
      { name: "invite [membre]", prefix: "tools", permission: null, description: "Affiche le nombre d'invitations d'un membre" },
      { name: "join channel del", prefix: "tools", permission: "server.welcome.manage", description: "Retire le salon d'annonce des arrivées" },
      { name: "join channel set [salon]", prefix: "tools", permission: "server.welcome.manage", description: "Règle le salon d'annonce des arrivées" },
      { name: "join embed off", prefix: "tools", permission: "server.welcome.manage", description: "Désactive l'embed d'arrivée" },
      { name: "join embed on", prefix: "tools", permission: "server.welcome.manage", description: "Active l'embed d'arrivée" },
      { name: "join embed set", prefix: "tools", permission: "server.welcome.manage", description: "Personnalise l'embed d'arrivée" },
      { name: "join embed test", prefix: "tools", permission: "server.welcome.manage", description: "Envoie un aperçu de l'embed d'arrivée" },
      { name: "join message <message>", prefix: "tools", permission: "server.welcome.manage", description: "Personnalise le message d'arrivée" },
      { name: "leaderboard event", prefix: "tools", permission: null, description: "Affiche le classement des événements" },
      { name: "leaderboard invite", prefix: "tools", permission: null, description: "Affiche le classement des invitations" },
      { name: "leave channel del", prefix: "tools", permission: "server.welcome.manage", description: "Retire le salon d'annonce des départs" },
      { name: "leave channel set [salon]", prefix: "tools", permission: "server.welcome.manage", description: "Règle le salon d'annonce des départs" },
      { name: "leave embed off", prefix: "tools", permission: "server.welcome.manage", description: "Désactive l'embed de départ" },
      { name: "leave embed on", prefix: "tools", permission: "server.welcome.manage", description: "Active l'embed de départ" },
      { name: "leave embed set", prefix: "tools", permission: "server.welcome.manage", description: "Personnalise l'embed de départ" },
      { name: "leave embed test", prefix: "tools", permission: "server.welcome.manage", description: "Envoie un aperçu de l'embed de départ" },
      { name: "leave message <message>", prefix: "tools", permission: "server.welcome.manage", description: "Personnalise le message de départ" },
      { name: "leavereset event <on/off>", prefix: "tools", permission: "server.welcome.manage", description: "Réinitialise le compteur d'événements d'un membre à son départ" },
      { name: "leavereset invite <on/off>", prefix: "tools", permission: "server.welcome.manage", description: "Réinitialise le compteur d'invitations d'un membre à son départ" },
      { name: "leavereset xp <on/off>", prefix: "tools", permission: "server.welcome.manage", description: "Réinitialise l'XP d'un membre à son départ" },
      { name: "list invite [membre]", prefix: "tools", permission: null, description: "Liste le détail des invitations d'un membre" },
      { name: "list join [membre]", prefix: "tools", permission: null, description: "Liste les membres invités par une personne" },
      { name: "list vanity", prefix: "tools", permission: null, description: "Affiche les arrivées via l'URL personnalisée du serveur" },
      { name: "manageevent add <nombre> [membre]", prefix: "tools", permission: "server.levels.manage", description: "Ajoute des événements à un membre" },
      { name: "manageevent del <nombre> [membre]", prefix: "tools", permission: "server.levels.manage", description: "Retire des événements à un membre" },
      { name: "manageevent reset <membre>", prefix: "tools", permission: "server.levels.manage", description: "Réinitialise les événements d'un membre" },
      { name: "manageevent resetall", prefix: "tools", permission: "server.levels.manage", description: "Réinitialise les événements de tout le serveur" },
      { name: "manageinvite add <nombre> [membre]", prefix: "tools", permission: "server.levels.manage", description: "Ajoute des invitations à un membre" },
      { name: "manageinvite del <nombre> [membre]", prefix: "tools", permission: "server.levels.manage", description: "Retire des invitations à un membre" },
      { name: "manageinvite reset <membre>", prefix: "tools", permission: "server.levels.manage", description: "Réinitialise les invitations d'un membre" },
      { name: "manageinvite resetall", prefix: "tools", permission: "server.levels.manage", description: "Réinitialise les invitations de tout le serveur" },
      { name: "role event add <role> <nombre>", prefix: "tools", permission: "server.levels.manage", description: "Attribue un rôle à partir d'un nombre d'événements" },
      { name: "role event del <role>", prefix: "tools", permission: "server.levels.manage", description: "Retire un rôle d'événements configuré" },
      { name: "role event list", prefix: "tools", permission: "server.levels.manage", description: "Liste les rôles d'événements configurés" },
      { name: "role invite add <role> <nombre>", prefix: "tools", permission: "server.levels.manage", description: "Attribue un rôle à partir d'un nombre d'invitations" },
      { name: "role invite cumul <on/off>", prefix: "tools", permission: "server.levels.manage", description: "Active/désactive le cumul des rôles d'invitation" },
      { name: "role invite del <role>", prefix: "tools", permission: "server.levels.manage", description: "Retire un rôle d'invitation configuré" },
      { name: "role invite list", prefix: "tools", permission: "server.levels.manage", description: "Liste les rôles d'invitation configurés" },
      { name: "settings invite", prefix: "tools", permission: "server.levels.manage", description: "Affiche l'ensemble des réglages du module Invitations" },
    ],
  },
  {
    key: "servertools",
    label: "Gestion du serveur",
    commands: [
      { name: "badge <emoji>", prefix: "tools", permission: null, description: "Ajoute un badge personnalisé disponible sur les profils" },
      { name: "managerep add <nombre> [membre]", prefix: "tools", permission: "server.levels.manage", description: "Ajoute de la réputation à un membre" },
      { name: "managerep del <nombre> [membre]", prefix: "tools", permission: "server.levels.manage", description: "Retire de la réputation à un membre" },
      { name: "picart", prefix: "tools", permission: null, description: "Transforme une image en rendu artistique" },
      { name: "ping", prefix: "tools", permission: null, description: "Affiche la latence du bot" },
      { name: "prefix <prefix>", prefix: "tools", permission: "sys", description: "Change le préfixe du système Tools" },
      { name: "profil-badge <cible> <emoji>", prefix: "tools", permission: "server.levels.manage", description: "Attribue un badge de profil à un membre" },
      { name: "profil-put <membre> <champ> [valeur]", prefix: "tools", permission: "server.levels.manage", description: "Modifie un champ du profil d'un membre" },
      { name: "public allow [salon]", prefix: "tools", permission: "protection.automod", description: "Autorise un salon en mode public" },
      { name: "public deny [salon]", prefix: "tools", permission: "protection.automod", description: "Retire l'autorisation d'un salon en mode public" },
      { name: "reset server", prefix: "tools", permission: "sys", description: "Réinitialise les réglages Tools du serveur" },
      { name: "settings ephemeral", prefix: "tools", permission: "sys", description: "Règle si les réponses Tools sont éphémères par défaut" },
      { name: "settings profil", prefix: "tools", permission: "sys", description: "Configure l'affichage des profils" },
    ],
  },
  {
    key: "botcontroltools",
    label: "Contrôle du bot",
    commands: [
      { name: "autoupdate <on/off>", prefix: "tools", permission: "sys", description: "Active/désactive l'autoupdate (voir aussi &autoupdate)" },
      { name: "changelog", prefix: "tools", permission: null, description: "Affiche les dernières notes de mise à jour" },
      { name: "clearowners", prefix: "tools", permission: "sys", description: "Supprime tous les owners du bot (voir aussi &clear owners)" },
      { name: "compet [text]", prefix: "tools", permission: "sys", description: "Change l'activité du bot (voir aussi &compet)" },
      { name: "dnd", prefix: "tools", permission: "sys", description: "Change le statut du bot (voir aussi &dnd)" },
      { name: "helptype <button/select/hybrid>", prefix: "tools", permission: "sys", description: "Change le mode de navigation du menu help" },
      { name: "idle", prefix: "tools", permission: "sys", description: "Change le statut du bot (voir aussi &idle)" },
      { name: "invisible", prefix: "tools", permission: "sys", description: "Change le statut du bot (voir aussi &invisible)" },
      { name: "listen [text]", prefix: "tools", permission: "sys", description: "Change l'activité du bot (voir aussi &listen)" },
      { name: "mainprefix [prefix]", prefix: "tools", permission: "sys", description: "Change le préfixe par défaut du bot" },
      { name: "mode <text/hybrid/slash>", prefix: "tools", permission: "sys", description: "Change le mode de commandes du bot" },
      { name: "mybots", prefix: "tools", permission: "sys", description: "Liste les bots gérés par ce compte" },
      { name: "online", prefix: "tools", permission: "sys", description: "Change le statut du bot (voir aussi &online)" },
      { name: "owner [membre]", prefix: "tools", permission: "sys", description: "Donne/affiche le grade Owner (voir aussi &owner)" },
      { name: "playto [text]", prefix: "tools", permission: "sys", description: "Change l'activité du bot (voir aussi &playto)" },
      { name: "remove-activity", prefix: "tools", permission: "sys", description: "Supprime l'activité du bot (voir aussi &remove activity)" },
      { name: "safejoin <temps>", prefix: "tools", permission: "sys", description: "Délai de sécurité avant qu'un nouveau membre puisse agir sur le serveur" },
      { name: "securinvite <on/off>", prefix: "tools", permission: "sys", description: "Le bot quitte automatiquement un serveur sans son propriétaire" },
      { name: "server invite <serveur>", prefix: "tools", permission: "sys", description: "Envoie une invitation pour un serveur où se trouve le bot" },
      { name: "server leave [serveur]", prefix: "tools", permission: "sys", description: "Fait quitter un serveur au bot" },
      { name: "server list", prefix: "tools", permission: "sys", description: "Affiche la liste des serveurs où se trouve le bot" },
      { name: "set banner [image] [lien]", prefix: "tools", permission: "sys", description: "Change la bannière du bot (voir aussi &set banner)" },
      { name: "set name <nom>", prefix: "tools", permission: "sys", description: "Change le nom du bot (voir aussi &set name)" },
      { name: "set pic [image] [lien]", prefix: "tools", permission: "sys", description: "Change la photo de profil du bot (voir aussi &set pic)" },
      { name: "set profil <nom> [pdp] [pdplink] [banner] [bannerlink]", prefix: "tools", permission: "sys", description: "Modifie d'un coup le profil du bot" },
      { name: "stream [text]", prefix: "tools", permission: "sys", description: "Change l'activité du bot (voir aussi &stream)" },
      { name: "unowner <membre>", prefix: "tools", permission: "sys", description: "Retire le grade Owner à quelqu'un" },
      { name: "updatebot", prefix: "tools", permission: "sys", description: "Installe les dernières mises à jour disponibles" },
      { name: "watch [text]", prefix: "tools", permission: "sys", description: "Change l'activité du bot (voir aussi &watch)" },
      { name: "wl add [serveur]", prefix: "tools", permission: "sys", description: "Ajoute un serveur à la whitelist d'invitation du bot" },
      { name: "wl clear", prefix: "tools", permission: "sys", description: "Vide la whitelist d'invitation du bot" },
      { name: "wl del [serveur]", prefix: "tools", permission: "sys", description: "Retire un serveur de la whitelist d'invitation du bot" },
      { name: "wl show", prefix: "tools", permission: "sys", description: "Affiche la whitelist d'invitation du bot" },
    ],
  },
  {
    key: "public",
    label: "Commandes publiques",
    commands: [
      { name: "bday <date>", prefix: "tools", permission: null, description: "Enregistre ta date d'anniversaire" },
      { name: "clear-prevnames", prefix: "tools", permission: null, description: "Efface ton historique de pseudos" },
      { name: "crowbots", prefix: "tools", permission: null, description: "Donne un lien d'invitation vers le serveur de support du bot" },
      { name: "help [module]", prefix: "tools", permission: null, description: "Affiche l'aide du système Tools" },
      { name: "leaderboard rep", prefix: "tools", permission: null, description: "Affiche le classement de réputation" },
      { name: "prevnames [membre]", prefix: "tools", permission: null, description: "Affiche l'historique de pseudos d'un membre" },
      { name: "profil [membre]", prefix: "tools", permission: null, description: "Affiche le profil d'un membre" },
      { name: "profil-set <champ> [valeur]", prefix: "tools", permission: null, description: "Personnalise ton propre profil" },
      { name: "rep <membre>", prefix: "tools", permission: null, description: "Donne un point de réputation à un membre" },
    ],
  },
];

/**
 * Catégories réellement utilisables par quelqu'un, commandes filtrées selon
 * ses droits — même logique que utils/commandCatalog.js::categoriesFor.
 * @param {(permission: string|null) => boolean} canUse
 */
function categoriesFor(canUse) {
  return CATEGORIES.map((category) => ({
    ...category,
    commands: category.commands.filter((cmd) => canUse(cmd.permission)),
  })).filter((category) => category.commands.length > 0);
}

module.exports = { CATEGORIES, categoriesFor };
